[package]
name = "egui_image"
version = "0.1.0"
authors = ["Lucas Walter <wsacul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "csv_plot"
path = "src/csv_plot.rs"

[[bin]]
name = "csv_plot_image"
path = "src/plot.rs"


[dependencies]
csv = "1.1"
eframe = "0.8.0" # Gives us egui, epi and web+native backends
image = "0.23" # { version = "0.23", default_features = false, features = ["jpeg", "png"], optional = true }
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
# http = ["eframe/http"] # Enable if you want to do http requests
persistence = ["eframe/persistence", "serde"] # Enable if you want to persist app state on shutdown

[profile.release]
opt-level = 2 # fast and small wasm
